on:
  push:
    tags:
      - '*'

name:
  'Create Release from Tag'

jobs:
  create_changelog_and_release:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: Check out repo content
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
  
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
          cache: npm
  
      - name: Install dependencies
        run: npm install octokit
  
      - name: Generate Release Notes
        run: |
          node index.js
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Changelog
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: update changelog'
          add: 'CHANGELOG.md'
          committer_name: GitHub Actions
          committer_email: actions@github.com
          push: 'origin main --force'
