on:
  push:
    tags:
      - '*'

name:
  'Create Release from Tag'

jobs:
  create_changelog_and_release:
    runs-on: ubuntu-latest
    permissions:
      issues: read

    steps:
      - name: Check out repo content
        uses: actions/checkout@v3
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
          cache: npm
  
      - name: Install dependencies
        run: npm install
  
      - name: Generate Release Notes
        run: |
          node index.js
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Changelog
        run: |
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG.md [skip ci]"
          git push
